name: Vercel Preview Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci

      - name: Check typescript
        run: npm run type:check

      - name: Check eslint
        run: npm run lint
